In [2]:
import torch
print(torch.__version__)

1.7.1+cpu


In [3]:
scaler=torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
vector=torch.tensor([7,1])
vector

tensor([7, 1])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix=torch.tensor([[1,2],
                   [3,4]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[1]

tensor([3, 4])

In [13]:
tensor=torch.tensor([[[1,2,3],
                     [4,5,6],
                     [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [23]:
tensor[0][2][2]

tensor(9)

In [26]:
tensor.ndim

3

In [34]:
random_tensor=torch.rand(2,4,2,5)
random_tensor

tensor([[[[0.2769, 0.8497, 0.4746, 0.1522, 0.6774],
          [0.8897, 0.6362, 0.4913, 0.3701, 0.5094]],

         [[0.6875, 0.9946, 0.1810, 0.6714, 0.5584],
          [0.7133, 0.2271, 0.4070, 0.2804, 0.7815]],

         [[0.4338, 0.2578, 0.3029, 0.5753, 0.2578],
          [0.2711, 0.5176, 0.0341, 0.5550, 0.7379]],

         [[0.3437, 0.6396, 0.0576, 0.6754, 0.5955],
          [0.8419, 0.2555, 0.1063, 0.7639, 0.3698]]],


        [[[0.2439, 0.7325, 0.3053, 0.8170, 0.5375],
          [0.4962, 0.7359, 0.8819, 0.2307, 0.2072]],

         [[0.2585, 0.9127, 0.4031, 0.1373, 0.6507],
          [0.9421, 0.5048, 0.4543, 0.7386, 0.0905]],

         [[0.8391, 0.1765, 0.6356, 0.7020, 0.7907],
          [0.4585, 0.2841, 0.3872, 0.2999, 0.3338]],

         [[0.0475, 0.1448, 0.0209, 0.2888, 0.9769],
          [0.2441, 0.5364, 0.2089, 0.0147, 0.4333]]]])

In [35]:
random_tensor.ndim

4

In [37]:
#zeros and ones
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
ones=torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [40]:
ones.dtype

torch.float32

In [41]:
torch.range(1,10)

<ipython-input-41-a2647884754e>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [43]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
torch_range=torch.arange(start=1,end=100,step=5)

In [47]:
torch.zeros_like(input=(torch_range))

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
#Tensor data type
float32=torch.tensor([1.0,2.2,3.1],dtype=None)
float32

tensor([1.0000, 2.2000, 3.1000])

In [51]:
float32.dtype

torch.float32

In [53]:
#Tensor data type
float32=torch.tensor([1.0,2.2,3.1],dtype=torch.float16)
float32

tensor([1.0000, 2.1992, 3.0996], dtype=torch.float16)

In [54]:
float32.dtype

torch.float16

In [57]:
float32=torch.tensor([1.0,2.2,3.1],dtype=None, #what data type is tensor(float32 float16 and float 64)
                                    device=None, #what divice is your tensor on
                                    requires_grad=False) #weather or not to track gradients with this tensors operations
float32

tensor([1.0000, 2.2000, 3.1000])

In [58]:
float_16=float32.type(torch.float16)
float_16

tensor([1.0000, 2.1992, 3.0996], dtype=torch.float16)

In [59]:
#Manipulating the Tensor
#Addition
#sutraction
#Multiplication(element wise)
#Matrix Multiplication

tensor=torch.tensor([1,2,3])
tensor+10



tensor([11, 12, 13])

In [60]:
tensor*10

tensor([10, 20, 30])

In [61]:
#builtin functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [65]:
#matrix Multiplication
#1.Element wise Multiplication
print(f"Equals:",{tensor*tensor})

Equals: {tensor([1, 4, 9])}


In [66]:
#Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [69]:
%%time
value=0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 859 µs, sys: 85 µs, total: 944 µs
Wall time: 597 µs


In [70]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 159 µs, sys: 15 µs, total: 174 µs
Wall time: 110 µs


tensor(14)

In [ ]:
#There are two main rules that performing matrix mutliplication needs to satisfy:
#The inner dimensions must match
#(3,2)@(3,2) will not work
#(2,3)@(3,2) will work
#(3,2)@(2,3) Will work

#The resulting matrix has the shape of the outer dimensions
#(2,3)@(3,2)->(2,2)
#(3,2)@(2,3)->(3,3)

In [75]:
#one of the most common error in deep learning:Shape error
tensor_A=torch.tensor([[1,2],
          [3,4],
          [5,6]])
tensor_B=torch.tensor([[11,12],
          [13,14],
          [15,16]])

In [76]:
result=torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [77]:
result=torch.matmul(tensor_A,tensor_B.T)

In [79]:
result,result.shape

(tensor([[ 35,  41,  47],
         [ 81,  95, 109],
         [127, 149, 171]]),
 torch.Size([3, 3]))

In [81]:
#Finding min max mean sum etc(tensor aggregation)
x=torch.arange(1,20,2)
x.dtype

torch.int64

In [83]:
x.min(),torch.min(x)

(tensor(1), tensor(1))

In [84]:
x.max(),torch.max(x)

(tensor(19), tensor(19))

In [85]:
torch.mean(x)

RuntimeError: Can only calculate the mean of floating types. Got Long instead.

In [88]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(10.), tensor(10.))

In [89]:
torch.sum(x),x.sum()

(tensor(100), tensor(100))

In [92]:
#Finding the positional min and max
x
#Find the position in tensor that has the minimum value with argmin()-->returns indux position of target tensor where the mimimum value occurs
x.argmin(),x[0]

(tensor(0), tensor(1))

In [93]:
#Find the position in tensor that has the minimum value with argmax()
x.argmax()

tensor(9)

In [ ]:
#Reshaping Stacking Squeezing and UnSqueezing tensors
#Reshaping: an input tensor to a defined shape
# View  :return a view of an input tensor of certain shape but keep the same memory as original tensor
# Stacking :combine  multiple tensors on top of each other(vstack) or side by side (hstack)
# Squeezing: Rempve all 1 dimensions  form a tensor
# Unsueezing :add 1 dimensions to a target tensor
# Premute: Return a view of the input with dimension permuted(swapped) in a certain way

In [104]:
y=torch.arange(1,10)
y,y.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [138]:
y_reshape=y.reshape(1,9)
y_reshape,y_reshape.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [108]:
#Changing the View
z=y.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [111]:
#Changing the z will change the x because a view of a tensor shares the same memory as the original 
z[:,0]=5
z,y

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [114]:
#stacking of tensors on top of each other 
y_stacked=torch.stack([y,y,y,y,y], dim=0)
y_stacked


tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [139]:
#torch.squeeze()->removes all single dimensions form a target tensor
y,y_reshape

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [140]:
z=y_reshape.squeeze()
z.shape

torch.Size([9])

In [141]:
y_reshape.shape

torch.Size([1, 9])

In [149]:
#unsqueeze
y_unsqueezed=y_reshape.unsqueeze(dim=0)
print(f'unsqeezed--------->{y_unsqueezed}')
print(f"shape---->{y_unsqueezed.shape}")

unsqeezed--------->tensor([[[5, 2, 3, 4, 5, 6, 7, 8, 9]]])
shape---->torch.Size([1, 1, 9])


In [162]:
#torch.permute:rearranges the dimensions of a target tensor in specified order
x_original=torch.rand(size=(224,224,3)) #[height,width,channels]

#permute the original tensor to rearrange the axis (or dim ) order
x_permute=x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(f"original shape:{x_original.shape}")
print(f"Prmuteed shape:{x_permute.shape}") #[channels,height,width]



original shape:torch.Size([224, 224, 3])
Prmuteed shape:torch.Size([3, 224, 224])


In [163]:
x_original

tensor([[[0.7380, 0.9258, 0.7056],
         [0.7315, 0.7527, 0.7094],
         [0.0859, 0.8625, 0.3171],
         ...,
         [0.8500, 0.8364, 0.8992],
         [0.0386, 0.8796, 0.8176],
         [0.6386, 0.8526, 0.7189]],

        [[0.2385, 0.8079, 0.5795],
         [0.7097, 0.8694, 0.0206],
         [0.7070, 0.4874, 0.5615],
         ...,
         [0.8618, 0.7518, 0.2891],
         [0.3988, 0.1034, 0.9230],
         [0.6574, 0.7117, 0.4933]],

        [[0.4615, 0.7063, 0.0271],
         [0.7225, 0.5097, 0.2067],
         [0.8263, 0.8290, 0.9008],
         ...,
         [0.6466, 0.6853, 0.9962],
         [0.1850, 0.3892, 0.4753],
         [0.6582, 0.6526, 0.0924]],

        ...,

        [[0.3464, 0.5355, 0.9786],
         [0.8736, 0.2360, 0.2733],
         [0.9630, 0.1557, 0.3964],
         ...,
         [0.1705, 0.8334, 0.1263],
         [0.4776, 0.3172, 0.7385],
         [0.9802, 0.2898, 0.2287]],

        [[0.5537, 0.6697, 0.8882],
         [0.5123, 0.7865, 0.2839],
         [0.

In [165]:
#Indexing in tensor(selecting data form tensor)
z=torch.arange(1,10).reshape(1,3,3)
z,z.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [167]:
print(z[0])
print(z[0,1,1])
print(z[0,2,1])
print(z[0,2,2])


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(5)
tensor(8)
tensor(9)


In [171]:
z[:,0]

tensor([[1, 2, 3]])

In [174]:
z[:,:,1]

tensor([[2, 5, 8]])

In [175]:
z[:,1,2]

tensor([6])

In [176]:
z[:,:,2]

tensor([[3, 6, 9]])

In [177]:
z[0,0,:]

tensor([1, 2, 3])

In [178]:
z[0,2,2]

tensor(9)

In [179]:
#Pytorch tensor and numpy
#Data in Numpy, want in pytorch tensor------->torch.from_numpy(ndarray)
#Pytorch tensor-------->Numpy---------->torch.Tensor.numpy()


In [185]:
#Numpy to tensor
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [186]:
#Tensor to Numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [1]:
#Reproducibility in Pytorch(Taking random out of random)
import torch
RANDOOM_SEED = 42
torch.manual_seed(RANDOOM_SEED)
random_tensor_A=torch.rand(3,4)

torch.manual_seed(RANDOOM_SEED)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
